version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run watch
    depends_on:
      - mysql
    env_file:
      - .env
    links:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proto_note
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
