#!/usr/bin/env bash

set -eux

docker-compose build
docker-compose run --rm -w '/app/admin' node yarn install
docker-compose run --rm -w '/app/client' node yarn install
docker-compose run --rm -w '/app/server' node yarn install
docker-compose run --rm -w '/app/server' node yarn run db-setup
